project: "[Project] SepReformer" ### Dont't change
notes: "SepReformer final version" ### Insert schanges(plz write details !!!)
# ------------------------------------------------------------------------------------------------------------------------------ #
config:
    # ------------------------------------------------------------ #
    dataset:
        max_len: 32000
        sampling_rate: 8000
        scp_dir: "data/scp_ss_8k"
        train:
            mixture: "tr_mix.scp"
            spk1: "tr_s1.scp"
            spk2: "tr_s2.scp"
            dynamic_mixing: false
        valid:
            mixture: "cv_mix.scp"
            spk1: "cv_s1.scp"
            spk2: "cv_s2.scp"
        test:
            mixture: "tt_mix.scp"
            spk1: "tt_s1.scp"
            spk2: "tt_s2.scp"
    # ------------------------------------------------------------ #
    dataloader:
        batch_size: 2
        pin_memory: false
        num_workers: 12
        drop_last: false
    # ------------------------------------------------------------ #
    model:
        num_stages: 4
        num_spks: 2
        module_audio_enc:
            in_channels: 1
            out_channels: 512
            kernel_size: 16
            stride: 8
            groups: 1
            bias: true
        module_feature_projector:
            num_channels: 512
            in_channels: 512
            out_channels: 256
            kernel_size: 3
            bias: true
        module_separator:
            num_stages: 4
            relative_positional_encoding:
                in_channels: 256
                num_heads: 8
                maxlen: 2000
                embed_v: false
            enc_stage:
                global_blocks:
                    in_channels: 256
                    num_mha_heads: 8
                    dropout_rate: 0.05
                local_blocks:
                    in_channels: 256
                    kernel_size: 65
                    dropout_rate: 0.05
                down_conv_layer:
                    in_channels: 256
                    samp_kernel_size: 5
            spk_split_stage:
                in_channels: 256
                num_spks: 2
            simple_fusion:
                out_channels: 256
            dec_stage:
                num_spks: 2
                global_blocks:
                    in_channels: 256
                    num_mha_heads: 8
                    dropout_rate: 0.05
                local_blocks:
                    in_channels: 256
                    kernel_size: 65
                    dropout_rate: 0.05
                spk_attention:
                    in_channels: 256
                    num_mha_heads: 8
                    dropout_rate: 0.05
        module_output_layer:
            in_channels: 512
            out_channels: 256
            num_spks: 2
        module_audio_dec:
            in_channels: 512
            out_channels: 1
            kernel_size: 16
            stride: 8
            bias: true
    # ------------------------------------------------------------ #
    criterion:
        name: ["PIT_SISNR_time"]
        PIT_SISNR_mag:
            frame_length: 512
            frame_shift: 128
            window: 'hann'
            num_stages: 4
            num_spks: 2
            scale_inv: true
            mel_opt: false
        PIT_SISNR_time:
            num_spks: 2
            scale_inv: true
        PIT_SISNRi:
            num_spks: 2
            scale_inv: true
        PIT_SDRi:
            dump: 0
    # ------------------------------------------------------------ #
    optimizer:
        name: ["AdamW"]
        AdamW:
            lr: 0.0001
            weight_decay: 0.01
    # ------------------------------------------------------------ #
    scheduler:
        name: ["ReduceLROnPlateau", "WarmupConstantSchedule"]
        ReduceLROnPlateau:
            mode: "min"
            min_lr: 1.0e-10
            factor: 0.8
            patience: 2
        WarmupConstantSchedule:
            warmup_steps: 1000
    # ------------------------------------------------------------ #
    check_computations:
        dummy_len: 16000
    # ------------------------------------------------------------ #
    engine:
        max_epoch: 100
        gpuid: "0"
        mvn: false
        clip_norm: 5
        start_scheduling: 50
        test_epochs: [100, 120, 150, 170]

training:
    batch_size: 32
    num_epochs: 100
    validation_interval: 1
    
    early_stopping:
        patience: 10
        min_delta: 0.0001
        
    checkpoint:
        save_interval: 1
        keep_best: true
        
data:
    sample_rate: 16000
    n_fft: 1024
    hop_length: 256
    
    augmentation:
        enabled: true
        gain:
            min_db: -10
            max_db: 10
        noise:
            snr_min: 10
            snr_max: 30
